"""Init

Revision ID: 2b9b2f89a0f4
Revises: 1e46e4a42954
Create Date: 2025-10-03 19:55:29.921701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9b2f89a0f4'
down_revision: Union[str, Sequence[str], None] = '1e46e4a42954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies_spa', sa.Column('model_count', sa.Integer(), nullable=True))
    op.add_column('agency_spa_applications', sa.Column('model_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_spa_applications', 'model_count')
    op.drop_column('agencies_spa', 'model_count')
    # ### end Alembic commands ###
