"""Init

Revision ID: 30c98dd2405c
Revises: e45534604014
Create Date: 2025-10-05 17:39:40.123368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c98dd2405c'
down_revision: Union[str, Sequence[str], None] = 'e45534604014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_spa_applications', sa.Column('teleram_id', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('teleram_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'teleram_id')
    op.drop_column('agency_spa_applications', 'teleram_id')
    # ### end Alembic commands ###
