"""Init

Revision ID: 3d7091f88713
Revises: 30c98dd2405c
Create Date: 2025-10-05 17:54:18.831062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7091f88713'
down_revision: Union[str, Sequence[str], None] = '30c98dd2405c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('telegram_id', sa.String(), nullable=True))
    op.drop_column('applications', 'teleram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('teleram_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'telegram_id')
    # ### end Alembic commands ###
