"""Init

Revision ID: 8e744f28977e
Revises: 
Create Date: 2025-09-25 16:05:58.175726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e744f28977e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies_spa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_agency', sa.Boolean(), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('agency_spa_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_agency', sa.Boolean(), nullable=True),
    sa.Column('photos', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('cupsize', sa.Integer(), nullable=True),
    sa.Column('clothsize', sa.Integer(), nullable=True),
    sa.Column('price_1h', sa.Float(), nullable=True),
    sa.Column('price_2h', sa.Float(), nullable=True),
    sa.Column('price_full_day', sa.Float(), nullable=True),
    sa.Column('main_photo', sa.String(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('cupsize', sa.Integer(), nullable=True),
    sa.Column('clothsize', sa.Integer(), nullable=True),
    sa.Column('price_1h', sa.Float(), nullable=True),
    sa.Column('price_2h', sa.Float(), nullable=True),
    sa.Column('price_full_day', sa.Float(), nullable=True),
    sa.Column('main_photo', sa.String(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.Column('agency_spa_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['agency_spa_id'], ['agencies_spa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phonenumber')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masters')
    op.drop_table('applications')
    op.drop_table('agency_spa_applications')
    op.drop_table('agencies_spa')
    # ### end Alembic commands ###
