"""Add user_type and linked_profile_id to WorkUser

Revision ID: e45534604014
Revises: 2b9b2f89a0f4
Create Date: 2025-10-05 11:51:38.559783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45534604014'
down_revision: Union[str, Sequence[str], None] = '2b9b2f89a0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_users', sa.Column('user_type', sa.String(), nullable=True))
    op.add_column('work_users', sa.Column('linked_profile_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_users', 'linked_profile_id')
    op.drop_column('work_users', 'user_type')
    # ### end Alembic commands ###
